name: Deploy to Azure Container Apps

on:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    env:
      GITHUB_SHA: ${{ github.event.workflow_run.head_sha }}

    steps:
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Wait for image to be available
        run: sleep 60

      - name: Deploy to Container App
        uses: azure/container-apps-deploy-action@v1
        with:
          containerAppName: ca-devops-health-api
          resourceGroup: rg-devops-health-api
          imageToDeploy: ghcr.io/moh2200/devops-health-api:${{ github.event.workflow_run.head_sha }}
